name: "Remove DNS Record"
description: "Removes an existing CloudFlare DNS record"
author: "nxae"

inputs:
  id:
    description: "DNS record ID"
    required: false
  name:
    description: "DNS record name"
    required: false
  token:
    description: "CloudFlare API token"
    default: ${{ secrets.CLOUDFLARE_TOKEN }}
    required: true
  zone:
    description: "CloudFlare zone id"
    default: ${{ secrets.CLOUDFLARE_ZONE }}
    required: true

outputs:
  id:
    description: "id"
  name:
    description: "name"
runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "at-sign"
  color: "orange"